# Copyright (c) 2019-2023 Bastien Guerry <bzg@bzg.fr>
# SPDX-License-Identifier: EPL-2.0
# License-Filename: LICENSES/EPL-2.0.txt

FROM openjdk:8-alpine

ENV MAILGUN_API_KEY ${MAILGUN_API_KEY}
ENV MAILGUN_API_SECRET ${MAILGUN_API_SECRET}
ENV MAILJET_API_KEY ${MAILJET_API_KEY}
ENV MAILJET_API_SECRET ${MAILJET_API_SECRET}
ENV SUBSCRIBE_SMTP_LOGIN ${SUBSCRIBE_SMTP_LOGIN}
ENV SUBSCRIBE_SMTP_PASSWORD ${SUBSCRIBE_SMTP_PASSWORD}
ENV SUBSCRIBE_PORT ${SUBSCRIBE_PORT}
ENV SUBSCRIBE_BASEURL ${SUBSCRIBE_BASEURL}

WORKDIR /

ADD subscribe.jar subscribe.jar
COPY config.edn config.edn
CMD ["java", "-jar", "subscribe.jar"]
